
import { Language, CaseType, CaseStatus } from "./types";

export const BVA_LINK = "https://www.bva.bund.de/EN/Services/Citizens/ID-Documents-Law/Citizenship/citizenship_node.html";

// Default list
export const COMMON_DOCS = [
  "Application Form (Antrag)",
  "Birth Certificate (Applicant)",
  "Marriage Certificate (Applicant)",
  "Passport Copy",
  "Criminal Record (FBI/Police)"
];

export const CASE_SPECIFIC_DOCS: Record<CaseType, string[]> = {
  [CaseType.STAG_5]: [
    ...COMMON_DOCS,
    "Appendix_EER",
    "Ancestor Birth Certificate (Parent)",
    "Ancestor Marriage Certificate (Parent)",
    "Proof of German Citizenship (Parent/Grandparent)",
    "Deregistration (Abmeldebescheinigung)"
  ],
  [CaseType.ART_116]: [
    ...COMMON_DOCS,
    "Appendix_A",
    "Appendix_V",
    "Proof of Persecution / Loss",
    "Old German Passport/ID",
    "Naturalization Cert of Other Country"
  ],
  [CaseType.FESTSTELLUNG]: [
    ...COMMON_DOCS,
    "Appendix_V",
    "Form F",
    "Direct Lineage Birth Certs (back to 1914)",
    "Direct Lineage Marriage Certs",
    "Old German Passports"
  ],
  [CaseType.STAG_15]: [
    ...COMMON_DOCS,
    "Proof of residency in Germany (pre-1933)",
    "Proof of persecution",
    "Naturalization documents"
  ],
  [CaseType.STAG_8]: [...COMMON_DOCS, "Proof of Integration", "B1 Language Cert"],
  [CaseType.STAG_10]: [...COMMON_DOCS, "Renunciation of previous citizenship"],
  [CaseType.STAG_14]: [...COMMON_DOCS, "Decree of Naturalization"]
};

// Fallback
export const DOCUMENT_LIST = COMMON_DOCS;

export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
  "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia",
  "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde",
  "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros",
  "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica",
  "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini",
  "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada",
  "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia",
  "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati",
  "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
  "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands",
  "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco",
  "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria",
  "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay",
  "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis",
  "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia",
  "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia",
  "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland",
  "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago",
  "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
  "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];

export const STATUS_TRANSLATIONS: Record<Language, Record<CaseStatus, string>> = {
  en: {
    [CaseStatus.SUBMITTED]: "Submitted",
    [CaseStatus.PROTOCOL_RECEIVED]: "Aktenzeichen Received",
    [CaseStatus.ADDITIONAL_DOCS]: "Docs Requested",
    [CaseStatus.APPROVED]: "Approved (Urkunde)",
    [CaseStatus.CLOSED]: "Closed/Rejected"
  },
  es: {
    [CaseStatus.SUBMITTED]: "Enviado",
    [CaseStatus.PROTOCOL_RECEIVED]: "Aktenzeichen Recibido",
    [CaseStatus.ADDITIONAL_DOCS]: "Docs Adicionales",
    [CaseStatus.APPROVED]: "Aprobado (Urkunde)",
    [CaseStatus.CLOSED]: "Cerrado/Rechazado"
  },
  de: {
    [CaseStatus.SUBMITTED]: "Eingereicht",
    [CaseStatus.PROTOCOL_RECEIVED]: "Aktenzeichen Erhalten",
    [CaseStatus.ADDITIONAL_DOCS]: "Unterlagen angefordert",
    [CaseStatus.APPROVED]: "Eingebürgert (Urkunde)",
    [CaseStatus.CLOSED]: "Geschlossen/Abgelehnt"
  },
  it: {
    [CaseStatus.SUBMITTED]: "Inviato",
    [CaseStatus.PROTOCOL_RECEIVED]: "Aktenzeichen Ricevuto",
    [CaseStatus.ADDITIONAL_DOCS]: "Doc. Aggiuntivi",
    [CaseStatus.APPROVED]: "Approvato (Urkunde)",
    [CaseStatus.CLOSED]: "Chiuso/Respinto"
  },
  pt: {
    [CaseStatus.SUBMITTED]: "Enviado",
    [CaseStatus.PROTOCOL_RECEIVED]: "Aktenzeichen Recebido",
    [CaseStatus.ADDITIONAL_DOCS]: "Docs Adicionais",
    [CaseStatus.APPROVED]: "Aprovado (Urkunde)",
    [CaseStatus.CLOSED]: "Fechado/Rejeitado"
  }
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    title: "Citizenship Application Tracker",
    dashboard: "Dashboard",
    map: "World Map",
    faq: "FAQ & Glossary",
    aiModel: "AI Model",
    myCase: "My Case",
    login: "Login",
    logout: "Logout",
    statsTitle: "Community Statistics",
    totalCases: "Total Cases",
    activeCases: "Active Cases",
    pausedCases: "Paused (>12m)",
    avgProtocol: "Avg Subm → AZ",
    avgApproval: "Avg AZ → Cit",
    avgTotal: "Avg Subm → Cit",
    waitTime: "Current Waiting Time",
    waitingAverage: "Average",
    months: "months",
    save: "Save",
    saving: "Saving...",
    validationError: "Please fill in mandatory fields marked with *.",
    country: "Country",
    consulate: "Consulate / City (Optional)",
    caseType: "Case Type",
    submissionDate: "Submission Date",
    protocolDate: "Protocol Date (AZ)",
    docsDate: "Docs Request Date",
    approvalDate: "Urkunde Date",
    closedDate: "Closing Date",
    status: "Current Status",
    notifications: "Notifications",
    notifySameDate: "Notify me if submission date twin gets Protocol",
    notifySameMonth: "Notify me if Protocol month/year group gets Urkunde",
    notifySubmissionCohort: "Notify me on status changes in my Submission Month cohort",
    notifyProtocolCohort: "Notify me on status changes in my Protocol Month cohort",
    notificationTwin: "A case submitted on {date} just received their Protocol!",
    notificationCohort: "A case from your Protocol cohort ({date}) just received their Urkunde!",
    comments: "Comments / Notes",
    filterCountry: "Filter by Country",
    filterMonth: "Submission Month",
    filterYear: "Submission Year",
    allCountries: "All Countries",
    allMonths: "All Months",
    allYears: "All Years",
    allTypes: "All Case Types",
    disclaimer: "LEGAL NOTICE: This is a private, independent statistical project. It is NOT affiliated with the BVA or the German Government. Data is submitted voluntarily and anonymously. We adhere to data minimization principles; no official documents or PII are stored. By using this tool, you consent to the processing of your anonymous data for statistical purposes.",
    staleWarning: "Your case hasn't been updated in 12 months and is paused from stats.",
    updateNow: "Update Now",
    mapInstructions: "Select a region to view countries.",
    admin: "Creator Access",
    exportCSV: "Export Data (CSV)",
    importCSV: "Bulk Upload (CSV)",
    downloadTemplate: "Download CSV Template",
    adminLogin: "Creator Login",
    enterPin: "Enter Password",
    accessGranted: "Access Granted",
    successImport: "Cases imported successfully!",
    errorImport: "Error importing. Check file format.",
    contactOwner: "Contact creator of this tracker",
    contactIntro: "For bug reports, feature requests, or to claim an orphaned case.",
    contactRedditText: "You can reach the creator of this tracker on Reddit:",
    sendMessage: "Send Message",
    yourName: "Your Name",
    yourEmail: "Your Email",
    yourMessage: "Your Message",
    howToAskAZ: "How to ask for Aktenzeichen?",
    generateEmail: "Generate Email",
    docsChecklist: "Documents sent checklist (optional)",
    progress: "Estimated Progress",
    communityFeed: "Community Notes",
    predictTimeline: "Predict Timeline",
    addToCalendar: "Add to Calendar",
    aiPredictionTitle: "AI Case Prediction",
    aiPredictionDesc: "Using current community data to estimate your timeline.",
    aiPredictionDescSpecific: "Using specific waiting times for {type}.",
    estUrkunde: "Est. Urkunde Date",
    stdDev: "Std Dev",
    sampleSize: "Sample Size",
    auditLog: "Audit Log",
    downloadCard: "Download Case Card",
    compareMe: "Compare vs Average",
    compareMyTime: "My Time (months)",
    compareMyWait: "My Wait (months)",
    compareCohortAvg: "Cohort Avg (months)",
    compareDesc: "Comparison against approved cases from your same submission period.",
    successTicker: "Recently Approved",
    shareTitle: "Share your case!",
    loginEmailLabel: "E-mail",
    loginPlaceholder: "email@example.com",
    loginButton: "Continue with Email",
    loginGoogle: "Sign in with Gmail (Sim)",
    loginOr: "or",
    loginCheckInbox: "Check your inbox!",
    loginLinkSent: "Link sent to",
    loginOpenLink: "Open Access Link (Simulated)",
    loginGoBack: "Go back",
    loginWait: "Waiting for you to click the link...",
    cardApplicant: "APPLICANT",
    cardType: "TYPE",
    cardGenerated: "generated by tracker-de",
    timelineSubmitted: "Submitted",
    timelineProto: "Aktenzeichen",
    timelineUrkunde: "Urkunde",
    timelineClosed: "Closed",
    timelineStatus: "Status",
    stepSubmitted: "Submitted",
    stepProtocol: "Protocol",
    stepDecision: "Decision",
    maintenance: "Maintenance Mode",
    maintenanceMessage: "The creator is performing maintenance, please try again later.",
    claimPrompt: "Did you fill out the online Google Sheet before? Click here to link your case.",
    claimDesc: "Enter your username exactly as it appears in the spreadsheet, and we will associate your email with that user so you can edit and monitor your case from now on.",
    createPrompt: "Or create a new anonymous user below:",
    claimConflictError: "This username already has a different email associated with it. Please contact the spreadsheet owner if you believe this is an error.",
    welcome: "Welcome!",
    newEmailPrompt: "This email is new to us. How would you like to proceed?",
    createNew: "Create New",
    claimExisting: "Claim Existing",
    createProfileDesc: "Create a brand new anonymous profile linked to",
    chooseFantasyName: "Choose Fantasy Username",
    searchCase: "Search Case",
    searchPlaceholder: "Search by Name, Country, or Date...",
    noUnclaimed: "No unclaimed cases found matching search.",
    cancel: "Cancel",
    createUser: "Create User",
    claimCaseBtn: "Claim Case",
    attention: "Attention",
    aiAnalysis: "AI Analysis",
    filters: "Filters:",
    showing: "Showing:",
    ghostCases: "Ghost Cases",
    backToActive: "Back to Active",
    ownerAccess: "Creator Access",
    glossary: "Glossary",
    breakdownExample: "Breakdown Example",
    officialWebsite: "Official BVA Website",
    officialDesc: "Access official forms, leaflets, and legal information directly from the Federal Office.",
    visitBva: "Visit BVA",
    copyText: "Copy Text",
    copied: "Copied!",
    close: "Close",
    details: "Details",
    confidence: "Confidence",
    confHigh: "High",
    confMedium: "Medium",
    confLow: "Low",
    avgWait: "Avg Wait",
    aiReasoning: "AI Reasoning",
    runModel: "Run the model to see your estimated date.",
    noCasesFound: "No cases found matching filters.",
    clickToView: "(Click segments to view cases)",
    statusDist: "Status Distribution",
    registeredEmail: "Registered Email",
    emailPending: "PENDING EMAIL",
    emailPendingDesc: "Case pending owner claim.",
    usernameTaken: "Username already taken.",
    usernameShort: "Username too short.",
    selectCase: "Please select a case to claim.",
    googleLoginFailed: "Google Login Failed",
    confirmEmail: "Confirm Your Email",
    confirm: "Confirm",
    edit: "Edit",
    ensureEmail: "Please ensure this email is correct. You will need to enter this exact email to access your case data in the future.",
    daysAvg: "days avg",
    untilToday: "until today",
    glossaryStag: "\"StAG\" stands for \"Staatsangehörigkeitsgesetz\", which is the German Nationality Act. Each paragraph or section of this law is numbered (e.g., §5, §10, etc.).",
    glossaryStag5: "Declaration of citizenship for children born to a German parent who did not receive citizenship by birth due to gender-discriminatory laws formerly in place.",
    glossaryStag15: "Restoration of citizenship for descendants of victims of Nazi persecution (1933-1945) who lost rights or were denied naturalization, but were not formally stripped of citizenship.",
    glossaryStag14: "Naturalization from abroad for those with strong ties to Germany (language, family, property) and public interest. Harder to qualify for than entitlement paths.",
    glossaryStag10: "Standard naturalization for residents in Germany (typically after 5-8 years), requiring B1 language, integration test, and financial stability.",
    glossaryBva: "Federal Office of Administration. It is a German federal government agency responsible for various administrative tasks, including citizenship applications from abroad.",
    glossaryAkz: "Reference number or case number assigned to your file. Example: \"ST1-2022 0501 0020-EER\". Use this number when contacting the office.",
    glossaryAkzBreakdown: "Department/Team, Year, Date code, Sequential number, Declaration type.",
    akzDepartment: "ST1 Department / Team Code",
    akzYear: "Year of Application",
    akzDate: "Date Code (MMDD)",
    akzSequential: "Sequential Number",
    akzType: "Declaration Type (e.g. EER)",
    glossaryUrkunde: "The official Citizenship Certificate. Receiving this means your application has been fully approved.",
    glossaryFeststellung: "Determination of Citizenship. For those who believe they are already citizens by descent but need to prove it.",
    glossaryArt116: "Restoration of citizenship for victims of Nazi persecution and their descendants (specifically those deprived of citizenship by the 1935 decree).",
    copyEmail: "Copy Email",
    contactNote: "Nota: This form opens your default email client (e.g. Outlook). If nothing happens, please copy the email address below.",
    lastUpdatedLabel: "Last updated:",
    privacyTitle: "Privacy Policy",
    acceptPrivacy: "I have read the Privacy Policy and agree to the processing of my data.",
    privacyLink: "Privacy Policy",
    privacyContent: "We store your email exclusively for authentication and to allow you to edit your case in the future. We do not sell or share your email with third parties. Your fantasy username is public, but your email is private.",
    faqGenDesc: "This tool generates a polite German email inquiry for the BVA. Fill in your details below.",
    faqFullName: "Full Name",
    faqDob: "Date of Birth",
    faqSubDate: "Submission Date",
    faqEmbassy: "Consulate / Embassy",
    faqResidence: "Place of Residence",
    faqEmailBvaBtn: "Open Email Client",
    legalDisclaimer: "Legal Disclaimer",
    simpleMode: "Simple Mode",
    scenicMode: "Scenic Mode",
    shuffle: "Shuffle"
  },
  es: {
    title: "Rastreador de Ciudadanía Alemana",
    dashboard: "Panel",
    map: "Mapa Mundial",
    faq: "Preguntas Frecuentes",
    aiModel: "Predicción IA",
    myCase: "Mi Caso",
    login: "Entrar",
    logout: "Salir",
    statsTitle: "Estadísticas de la Comunidad",
    totalCases: "Total Casos",
    activeCases: "Casos Activos",
    pausedCases: "Pausados (>12m)",
    avgProtocol: "Promedio Envio → AZ",
    avgApproval: "Promedio AZ → Urkunde",
    avgTotal: "Total Envio → Urkunde",
    waitTime: "Tiempo de Espera Actual",
    waitingAverage: "Promedio",
    months: "meses",
    save: "Guardar",
    saving: "Guardando...",
    validationError: "Por favor complete los campos obligatorios marcados con *.",
    country: "País",
    consulate: "Consulado / Ciudad (Opcional)",
    caseType: "Tipo de Caso",
    submissionDate: "Fecha de Envío",
    protocolDate: "Fecha de Protocolo (AZ)",
    docsDate: "Fecha Solicitud Docs",
    approvalDate: "Fecha de Urkunde",
    closedDate: "Fecha de Cierre",
    status: "Estado Actual",
    notifications: "Notificaciones",
    notifySameDate: "Avisarme si alguien con mi fecha de envío recibe Protocolo",
    notifySameMonth: "Avisarme si mi grupo de mes/año recibe Urkunde",
    notifySubmissionCohort: "Notificarme cambios en mi cohorte de Mes de Envío",
    notifyProtocolCohort: "Notificarme cambios en mi cohorte de Mes de Protocolo",
    notificationTwin: "¡Un caso enviado el {date} acaba de recibir su Protocolo!",
    notificationCohort: "¡Un caso de tu cohorte de Protocolo ({date}) acaba de recibir su Urkunde!",
    comments: "Comentarios / Notas",
    filterCountry: "Filtrar por País",
    filterMonth: "Mes de Envío",
    filterYear: "Año de Envío",
    allCountries: "Todos los Países",
    allMonths: "Todos los Meses",
    allYears: "Todos los Años",
    allTypes: "Todos los Tipos",
    disclaimer: "AVISO LEGAL: Este es un proyecto estadístico privado e independiente. NO está afiliado con el BVA ni con el Gobierno Alemán. Los datos se envían voluntaria y anónimamente. No almacenamos documentos oficiales ni PII.",
    staleWarning: "Tu caso no se ha actualizado en 12 meses y está pausado de las estadísticas.",
    updateNow: "Actualizar Ahora",
    mapInstructions: "Selecciona una región para ver países.",
    admin: "Acceso Creador",
    exportCSV: "Exportar Datos (CSV)",
    importCSV: "Carga Masiva (CSV)",
    downloadTemplate: "Descargar Plantilla CSV",
    adminLogin: "Login Creador",
    enterPin: "Ingresar Contraseña",
    accessGranted: "Acceso Permitido",
    successImport: "¡Casos importados exitosamente!",
    errorImport: "Error al importar. Verifique el formato.",
    contactOwner: "Contactar al creador",
    contactIntro: "Para reportes de errores, sugerencias o reclamar un caso huérfano.",
    contactRedditText: "Puedes contactar al creador de este rastreador en Reddit:",
    sendMessage: "Enviar Mensaje",
    yourName: "Tu Nombre",
    yourEmail: "Tu Email",
    yourMessage: "Tu Mensaje",
    howToAskAZ: "¿Cómo pedir el Aktenzeichen?",
    generateEmail: "Generar Email",
    docsChecklist: "Lista de documentos enviados (opcional)",
    progress: "Progreso Estimado",
    communityFeed: "Notas de la Comunidad",
    predictTimeline: "Predecir Cronograma",
    addToCalendar: "Añadir al Calendario",
    aiPredictionTitle: "Predicción de Caso IA",
    aiPredictionDesc: "Usando datos de la comunidad para estimar tu cronograma.",
    aiPredictionDescSpecific: "Usando tiempos de espera específicos para {type}.",
    estUrkunde: "Fecha Est. Urkunde",
    stdDev: "Desv. Estándar",
    sampleSize: "Tamaño Muestra",
    auditLog: "Registro Auditoría",
    downloadCard: "Descargar Tarjeta",
    compareMe: "Comparativa vs Promedio",
    compareMyTime: "Mi Tiempo (meses)",
    compareMyWait: "Mi Espera (meses)",
    compareCohortAvg: "Promedio Cohorte (meses)",
    compareDesc: "Comparación contra casos aprobados de tu mismo periodo.",
    successTicker: "Aprobados Recientemente",
    shareTitle: "¡Comparte tu caso!",
    loginEmailLabel: "Correo Electrónico",
    loginPlaceholder: "email@ejemplo.com",
    loginButton: "Continuar con Email",
    loginGoogle: "Entrar con Gmail (Sim)",
    loginOr: "o",
    loginCheckInbox: "¡Revisa tu bandeja de entrada!",
    loginLinkSent: "Enlace enviado a",
    loginOpenLink: "Abrir Enlace de Acceso (Simulado)",
    loginGoBack: "Volver",
    loginWait: "Esperando que hagas clic en el enlace...",
    cardApplicant: "SOLICITANTE",
    cardType: "TIPO",
    cardGenerated: "generado por tracker-de",
    timelineSubmitted: "Enviado",
    timelineProto: "Aktenzeichen",
    timelineUrkunde: "Urkunde",
    timelineClosed: "Cerrado",
    timelineStatus: "Estado",
    stepSubmitted: "Enviado",
    stepProtocol: "Protocolo",
    stepDecision: "Decisión",
    maintenance: "Modo Mantenimiento",
    maintenanceMessage: "El creador está realizando mantenimiento, por favor intente más tarde.",
    claimPrompt: "¿Llenaste la hoja de cálculo de Google antes? Haz clic aquí para vincular tu caso.",
    claimDesc: "Ingresa tu nombre de usuario exactamente como aparece en la hoja de cálculo, y asociaremos tu email para que puedas editar y monitorear tu caso.",
    createPrompt: "O crea un nuevo usuario anónimo abajo:",
    claimConflictError: "Este usuario ya tiene un email asociado. Contacta al dueño si crees que es un error.",
    welcome: "¡Bienvenido!",
    newEmailPrompt: "Este correo es nuevo para nosotros. ¿Cómo deseas proceder?",
    createNew: "Crear Nuevo",
    claimExisting: "Reclamar Existente",
    createProfileDesc: "Crear un perfil anónimo nuevo vinculado a",
    chooseFantasyName: "Elige Nombre de Fantasía",
    searchCase: "Buscar Caso",
    searchPlaceholder: "Buscar por Nombre, País o Fecha...",
    noUnclaimed: "No se encontraron casos sin reclamar.",
    cancel: "Cancelar",
    createUser: "Crear Usuario",
    claimCaseBtn: "Reclamar Caso",
    attention: "Atención",
    aiAnalysis: "Análisis IA",
    filters: "Filtros:",
    showing: "Mostrando:",
    ghostCases: "Casos Fantasma",
    backToActive: "Volver a Activos",
    ownerAccess: "Acceso Creador",
    glossary: "Glosario",
    breakdownExample: "Ejemplo de Desglose",
    officialWebsite: "Sitio Oficial BVA",
    officialDesc: "Acceda a formularios oficiales, folletos e información legal directamente de la Oficina Federal.",
    visitBva: "Visitar BVA",
    copyText: "Copiar Texto",
    copied: "¡Copiado!",
    close: "Cerrar",
    details: "Detalles",
    confidence: "Confianza",
    confHigh: "Alta",
    confMedium: "Media",
    confLow: "Baja",
    avgWait: "Espera Promedio",
    aiReasoning: "Razonamiento IA",
    runModel: "Ejecuta el modelo para ver tu fecha estimada.",
    noCasesFound: "No se encontraron casos con los filtros actuales.",
    clickToView: "(Clic para ver casos)",
    statusDist: "Distribución de Estado",
    registeredEmail: "Email Registrado",
    emailPending: "EMAIL PENDIENTE",
    emailPendingDesc: "Caso pendiente de reclamo.",
    usernameTaken: "Nombre de usuario ya tomado.",
    usernameShort: "Nombre muy corto.",
    selectCase: "Por favor selecciona un caso.",
    googleLoginFailed: "Fallo Login Google",
    confirmEmail: "Confirma Tu Email",
    confirm: "Confirmar",
    edit: "Editar",
    ensureEmail: "Asegúrate que este email es correcto. Lo necesitarás para acceder a tus datos en el futuro.",
    daysAvg: "días promedio",
    untilToday: "hasta hoy",
    glossaryStag: "\"StAG\" significa \"Staatsangehörigkeitsgesetz\" (Ley de Nacionalidad Alemana).",
    glossaryStag5: "Declaración de ciudadanía para hijos nacidos de padre/madre alemán que no recibieron ciudadanía por leyes discriminatorias de género.",
    glossaryStag15: "Restitución para descendientes de víctimas de persecución Nazi (1933-1945).",
    glossaryStag14: "Naturalización desde el extranjero por lazos fuertes con Alemania e interés público.",
    glossaryStag10: "Naturalización estándar para residentes en Alemania (5-8 años).",
    glossaryBva: "Oficina Federal de Administración. Agencia responsable de solicitudes desde el extranjero.",
    glossaryAkz: "Número de referencia de tu expediente. Ejemplo: \"ST1-2022 0501 0020-EER\".",
    glossaryAkzBreakdown: "Departamento/Equipo, Año, Código Fecha, Número Secuencial, Tipo Declaración.",
    akzDepartment: "ST1 Código de Departamento / Equipo",
    akzYear: "Año de Aplicación",
    akzDate: "Código de Fecha (MMDD)",
    akzSequential: "Número Secuencial",
    akzType: "Tipo de Declaración (ej. EER)",
    glossaryUrkunde: "Certificado de Ciudadanía oficial. Recibirlo significa aprobación total.",
    glossaryFeststellung: "Determinación de Ciudadanía (Constatación).",
    glossaryArt116: "Restitución para víctimas de persecución Nazi (Art 116 Ley Fundamental).",
    copyEmail: "Copiar Email",
    contactNote: "Nota: Este formulario abre tu cliente de correo. Si no funciona, copia el email abajo.",
    lastUpdatedLabel: "Última act.:",
    privacyTitle: "Política de Privacidad",
    acceptPrivacy: "He leído la Política de Privacidad y acepto el procesamiento de mis datos.",
    privacyLink: "Política de Privacidad",
    privacyContent: "Almacenamos su correo electrónico exclusivamente para autenticación y para permitirle editar su caso en el futuro. No vendemos ni compartimos su correo electrónico con terceros. Su nombre de usuario de fantasía es público, pero su correo electrónico es privado.",
    faqGenDesc: "Esta herramienta genera un correo en alemán cortés para el BVA. Complete sus datos abajo.",
    faqFullName: "Nombre Completo",
    faqDob: "Fecha de Nacimiento",
    faqSubDate: "Fecha de Envío",
    faqEmbassy: "Consulado / Embajada",
    faqResidence: "Lugar de Residencia",
    faqEmailBvaBtn: "Abrir Cliente de Correo",
    legalDisclaimer: "Aviso Legal",
    simpleMode: "Modo Simple",
    scenicMode: "Modo Paisaje",
    shuffle: "Aleatorio"
  },
  de: {
    title: "Einbürgerung Tracker",
    dashboard: "Dashboard",
    map: "Weltkarte",
    faq: "FAQ & Glossar",
    aiModel: "KI-Modell",
    myCase: "Mein Fall",
    login: "Anmelden",
    logout: "Abmelden",
    statsTitle: "Community Statistik",
    totalCases: "Fälle Gesamt",
    activeCases: "Aktive Fälle",
    pausedCases: "Pausiert (>12m)",
    avgProtocol: "Ø Einreichung → AZ",
    avgApproval: "Ø AZ → Urkunde",
    avgTotal: "Ø Gesamt",
    waitTime: "Aktuelle Wartezeit",
    waitingAverage: "Durchschnitt",
    months: "Monate",
    save: "Speichern",
    saving: "Speichert...",
    validationError: "Bitte Pflichtfelder ausfüllen.",
    country: "Land",
    consulate: "Konsulat / Stadt (Optional)",
    caseType: "Falltyp",
    submissionDate: "Einreichungsdatum",
    protocolDate: "Aktenzeichen Datum",
    docsDate: "Dokumentenanforderung",
    approvalDate: "Urkundendatum",
    closedDate: "Schließungsdatum",
    status: "Aktueller Status",
    notifications: "Benachrichtigungen",
    notifySameDate: "Benachrichtigen bei AZ für gleiches Datum",
    notifySameMonth: "Benachrichtigen bei Urkunde für gleichen Monat",
    notifySubmissionCohort: "Benachrichtigen bei Änderungen in meiner Einreichungs-Kohorte",
    notifyProtocolCohort: "Benachrichtigen bei Änderungen in meiner Protokoll-Kohorte",
    notificationTwin: "Ein Fall vom {date} hat ein Aktenzeichen erhalten!",
    notificationCohort: "Ein Fall aus Ihrer Kohorte ({date}) hat die Urkunde erhalten!",
    comments: "Kommentare",
    filterCountry: "Nach Land filtern",
    filterMonth: "Monat",
    filterYear: "Jahr",
    allCountries: "Alle Länder",
    allMonths: "Alle Monate",
    allYears: "Alle Jahre",
    allTypes: "Alle Typen",
    disclaimer: "RECHTLICHER HINWEIS: Dies ist ein privates Projekt. NICHT verbunden mit dem BVA.",
    staleWarning: "Ihr Fall wurde seit 12 Monaten nicht aktualisiert.",
    updateNow: "Jetzt aktualisieren",
    mapInstructions: "Region wählen.",
    admin: "Admin Zugang",
    exportCSV: "Export CSV",
    importCSV: "Import CSV",
    downloadTemplate: "Vorlage herunterladen",
    adminLogin: "Admin Login",
    enterPin: "Passwort eingeben",
    accessGranted: "Zugriff gewährt",
    successImport: "Import erfolgreich!",
    errorImport: "Fehler beim Import.",
    contactOwner: "Ersteller kontaktieren",
    contactIntro: "Für Fehlerberichte oder Anfragen.",
    contactRedditText: "Kontakt auf Reddit:",
    sendMessage: "Nachricht senden",
    yourName: "Ihr Name",
    yourEmail: "Ihre E-Mail",
    yourMessage: "Ihre Nachricht",
    howToAskAZ: "Wie frage ich nach dem AZ?",
    generateEmail: "E-Mail generieren",
    docsChecklist: "Dokumentenliste (optional)",
    progress: "Fortschritt",
    communityFeed: "Community Notizen",
    predictTimeline: "Zeitlinie vorhersagen",
    addToCalendar: "Zum Kalender hinzufügen",
    aiPredictionTitle: "KI Vorhersage",
    aiPredictionDesc: "Schätzung basierend auf Community-Daten.",
    aiPredictionDescSpecific: "Verwendung spezifischer Wartezeiten für {type}.",
    estUrkunde: "Geschätztes Urkundendatum",
    stdDev: "Std Abw",
    sampleSize: "Stichprobe",
    auditLog: "Audit Log",
    downloadCard: "Karte herunterladen",
    compareMe: "Vergleich vs Durchschnitt",
    compareMyTime: "Meine Zeit (Monate)",
    compareMyWait: "Meine Wartezeit (Monate)",
    compareCohortAvg: "Kohorte Ø (Monate)",
    compareDesc: "Vergleich mit genehmigten Fällen aus demselben Zeitraum.",
    successTicker: "Kürzlich genehmigt",
    shareTitle: "Teile deinen Fall!",
    loginEmailLabel: "E-Mail",
    loginPlaceholder: "email@beispiel.de",
    loginButton: "Weiter mit E-Mail",
    loginGoogle: "Login mit Gmail (Sim)",
    loginOr: "oder",
    loginCheckInbox: "Prüfen Sie Ihren Posteingang!",
    loginLinkSent: "Link gesendet an",
    loginOpenLink: "Link öffnen (Simuliert)",
    loginGoBack: "Zurück",
    loginWait: "Warte auf Klick...",
    cardApplicant: "ANTRAGSTELLER",
    cardType: "TYP",
    cardGenerated: "generiert von tracker-de",
    timelineSubmitted: "Eingereicht",
    timelineProto: "Aktenzeichen",
    timelineUrkunde: "Urkunde",
    timelineClosed: "Geschlossen",
    timelineStatus: "Status",
    stepSubmitted: "Eingereicht",
    stepProtocol: "Protokoll",
    stepDecision: "Entscheidung",
    maintenance: "Wartungsmodus",
    maintenanceMessage: "Wartungsarbeiten im Gange, bitte später versuchen.",
    claimPrompt: "Haben Sie die Tabelle ausgefüllt? Hier klicken.",
    claimDesc: "Geben Sie Ihren Benutzernamen exakt ein.",
    createPrompt: "Oder neuen Benutzer erstellen:",
    claimConflictError: "Benutzername bereits vergeben.",
    welcome: "Willkommen!",
    newEmailPrompt: "Diese E-Mail ist neu. Wie möchten Sie fortfahren?",
    createNew: "Neu erstellen",
    claimExisting: "Bestehenden beanspruchen",
    createProfileDesc: "Neues Profil erstellen für",
    chooseFantasyName: "Fantasiename wählen",
    searchCase: "Fall suchen",
    searchPlaceholder: "Suchen...",
    noUnclaimed: "Keine freien Fälle gefunden.",
    cancel: "Abbrechen",
    createUser: "Benutzer erstellen",
    claimCaseBtn: "Fall beanspruchen",
    attention: "Achtung",
    aiAnalysis: "KI Analyse",
    filters: "Filter:",
    showing: "Zeige:",
    ghostCases: "Geisterfälle",
    backToActive: "Zurück zu Aktiv",
    ownerAccess: "Ersteller Zugang",
    glossary: "Glossar",
    breakdownExample: "Beispiel Aufschlüsselung",
    officialWebsite: "Offizielle BVA Webseite",
    officialDesc: "Zugang zu offiziellen Formularen und Informationen.",
    visitBva: "BVA Besuchen",
    copyText: "Text kopieren",
    copied: "Kopiert!",
    close: "Schließen",
    details: "Details",
    confidence: "Konfidenz",
    confHigh: "Hoch",
    confMedium: "Mittel",
    confLow: "Niedrig",
    avgWait: "Ø Wartezeit",
    aiReasoning: "KI Begründung",
    runModel: "Modell starten.",
    noCasesFound: "Keine Fälle gefunden.",
    clickToView: "(Klicken zum Anzeigen)",
    statusDist: "Statusverteilung",
    registeredEmail: "Registrierte E-Mail",
    emailPending: "E-MAIL AUSSTEHEND",
    emailPendingDesc: "Fall wartet auf Beanspruchung.",
    usernameTaken: "Name vergeben.",
    usernameShort: "Name zu kurz.",
    selectCase: "Bitte Fall wählen.",
    googleLoginFailed: "Google Login fehlgeschlagen",
    confirmEmail: "E-Mail bestätigen",
    confirm: "Bestätigen",
    edit: "Bearbeiten",
    ensureEmail: "Bitte stellen Sie sicher, dass die E-Mail korrekt ist.",
    daysAvg: "Tage Ø",
    untilToday: "bis heute",
    glossaryStag: "Staatsangehörigkeitsgesetz.",
    glossaryStag5: "Erklärungserwerb (Kinder deutscher Eltern).",
    glossaryStag15: "Wiedergutmachung (Nazi-Verfolgte).",
    glossaryStag14: "Ermessenseinbürgerung vom Ausland.",
    glossaryStag10: "Anspruchseinbürgerung (Inland).",
    glossaryBva: "Bundesverwaltungsamt.",
    glossaryAkz: "Aktenzeichen.",
    glossaryAkzBreakdown: "Abteilung, Jahr, Datum, Nummer, Typ.",
    akzDepartment: "Abteilungscode",
    akzYear: "Jahr",
    akzDate: "Datumscode",
    akzSequential: "Laufende Nummer",
    akzType: "Typ",
    glossaryUrkunde: "Einbürgerungsurkunde.",
    glossaryFeststellung: "Feststellung der deutschen Staatsangehörigkeit.",
    glossaryArt116: "Wiedergutmachung (Art 116 GG).",
    copyEmail: "E-Mail kopieren",
    contactNote: "Hinweis: Öffnet E-Mail-Client.",
    lastUpdatedLabel: "Zuletzt akt.:",
    privacyTitle: "Datenschutzerklärung",
    acceptPrivacy: "Ich stimme der Datenverarbeitung zu.",
    privacyLink: "Datenschutz",
    privacyContent: "Wir speichern Ihre E-Mail nur zur Authentifizierung.",
    faqGenDesc: "Generiert eine höfliche E-Mail an das BVA.",
    faqFullName: "Vollständiger Name",
    faqDob: "Geburtsdatum",
    faqSubDate: "Einreichungsdatum",
    faqEmbassy: "Konsulat / Botschaft",
    faqResidence: "Wohnort",
    faqEmailBvaBtn: "E-Mail Programm öffnen",
    legalDisclaimer: "Rechtlicher Hinweis",
    simpleMode: "Einfacher Modus",
    scenicMode: "Landschaftsmodus",
    shuffle: "Mischen"
  },
  it: {
    title: "Tracker Cittadinanza Tedesca",
    dashboard: "Cruscotto",
    map: "Mappa",
    faq: "FAQ & Glossario",
    aiModel: "Modello IA",
    myCase: "Il Mio Caso",
    login: "Accedi",
    logout: "Esci",
    statsTitle: "Statistiche Community",
    totalCases: "Totale Casi",
    activeCases: "Casi Attivi",
    pausedCases: "In Pausa",
    avgProtocol: "Media Invio → AZ",
    avgApproval: "Media AZ → Urkunde",
    avgTotal: "Media Totale",
    waitTime: "Tempo di Attesa",
    waitingAverage: "Media",
    months: "mesi",
    save: "Salva",
    saving: "Salvataggio...",
    validationError: "Compila i campi obbligatori.",
    country: "Paese",
    consulate: "Consolato",
    caseType: "Tipo Caso",
    submissionDate: "Data Invio",
    protocolDate: "Data Protocollo",
    docsDate: "Richiesta Doc",
    approvalDate: "Data Urkunde",
    closedDate: "Data Chiusura",
    status: "Stato Attuale",
    notifications: "Notifiche",
    notifySameDate: "Notifica se stessa data riceve AZ",
    notifySameMonth: "Notifica se stesso mese riceve Urkunde",
    notifySubmissionCohort: "Notificami aggiornamenti sulla mia coorte di invio",
    notifyProtocolCohort: "Notificami aggiornamenti sulla mia coorte di protocollo",
    notificationTwin: "Un caso del {date} ha ricevuto il Protocollo!",
    notificationCohort: "Un caso della tua coorte ({date}) ha ricevuto l'Urkunde!",
    comments: "Commenti",
    filterCountry: "Filtra per Paese",
    filterMonth: "Mese",
    filterYear: "Anno",
    allCountries: "Tutti i Paesi",
    allMonths: "Tutti i Mesi",
    allYears: "Tutti gli Anni",
    allTypes: "Tutti i Tipi",
    disclaimer: "AVVISO LEGALE: Progetto privato non affiliato al BVA.",
    staleWarning: "Il caso non è aggiornato da 12 mesi.",
    updateNow: "Aggiorna Ora",
    mapInstructions: "Seleziona regione.",
    admin: "Accesso Admin",
    exportCSV: "Esporta CSV",
    importCSV: "Importa CSV",
    downloadTemplate: "Scarica Modello",
    adminLogin: "Login Admin",
    enterPin: "Password",
    accessGranted: "Accesso Concesso",
    successImport: "Importato con successo!",
    errorImport: "Errore importazione.",
    contactOwner: "Contatta Creatore",
    contactIntro: "Per segnalazioni o reclami casi.",
    contactRedditText: "Contatta su Reddit:",
    sendMessage: "Invia Messaggio",
    yourName: "Tuo Nome",
    yourEmail: "Tua Email",
    yourMessage: "Messaggio",
    howToAskAZ: "Come chiedere AZ?",
    generateEmail: "Genera Email",
    docsChecklist: "Lista Documenti",
    progress: "Progresso",
    communityFeed: "Note Community",
    predictTimeline: "Prevedi Timeline",
    addToCalendar: "Aggiungi al Calendario",
    aiPredictionTitle: "Previsione IA",
    aiPredictionDesc: "Stima basata sui dati della community.",
    aiPredictionDescSpecific: "Utilizzando tempi di attesa specifici per {type}.",
    estUrkunde: "Data Est. Urkunde",
    stdDev: "Dev. Std",
    sampleSize: "Campione",
    auditLog: "Audit Log",
    downloadCard: "Scarica Scheda",
    compareMe: "Confronta vs Media",
    compareMyTime: "Mio Tempo (mesi)",
    compareMyWait: "Mia Attesa (mesi)",
    compareCohortAvg: "Media Coorte (mesi)",
    compareDesc: "Confronto con casi approvati dello stesso periodo.",
    successTicker: "Approvati Recenti",
    shareTitle: "Condividi il caso!",
    loginEmailLabel: "Email",
    loginPlaceholder: "email@esempio.com",
    loginButton: "Continua con Email",
    loginGoogle: "Accedi con Gmail (Sim)",
    loginOr: "o",
    loginCheckInbox: "Controlla la posta!",
    loginLinkSent: "Link inviato a",
    loginOpenLink: "Apri Link",
    loginGoBack: "Indietro",
    loginWait: "In attesa...",
    cardApplicant: "RICHIEDENTE",
    cardType: "TIPO",
    cardGenerated: "generato da tracker-de",
    timelineSubmitted: "Inviato",
    timelineProto: "Protocollo",
    timelineUrkunde: "Urkunde",
    timelineClosed: "Chiuso",
    timelineStatus: "Stato",
    stepSubmitted: "Inviato",
    stepProtocol: "Protocollo",
    stepDecision: "Decisione",
    maintenance: "Manutenzione",
    maintenanceMessage: "Manutenzione in corso, riprova più tardi.",
    claimPrompt: "Hai compilato il foglio Google? Clicca qui.",
    claimDesc: "Inserisci il nome utente esatto.",
    createPrompt: "O crea nuovo utente:",
    claimConflictError: "Utente già in uso.",
    welcome: "Benvenuto!",
    newEmailPrompt: "Email nuova. Come procedere?",
    createNew: "Crea Nuovo",
    claimExisting: "Reclama Esistente",
    createProfileDesc: "Crea nuovo profilo per",
    chooseFantasyName: "Scegli Nome Fantasia",
    searchCase: "Cerca Caso",
    searchPlaceholder: "Cerca...",
    noUnclaimed: "Nessun caso non reclamato.",
    cancel: "Annulla",
    createUser: "Crea Utente",
    claimCaseBtn: "Reclama Caso",
    attention: "Attenzione",
    aiAnalysis: "Analisi IA",
    filters: "Filtri:",
    showing: "Mostrando:",
    ghostCases: "Casi Fantasma",
    backToActive: "Torna ad Attivi",
    ownerAccess: "Accesso Creatore",
    glossary: "Glossario",
    breakdownExample: "Esempio",
    officialWebsite: "Sito BVA",
    officialDesc: "Accesso a moduli e info ufficiali.",
    visitBva: "Visita BVA",
    copyText: "Copia Testo",
    copied: "Copiato!",
    close: "Chiudi",
    details: "Dettagli",
    confidence: "Fiducia",
    confHigh: "Alta",
    confMedium: "Media",
    confLow: "Bassa",
    avgWait: "Attesa Media",
    aiReasoning: "Ragionamento IA",
    runModel: "Esegui modello.",
    noCasesFound: "Nessun caso trovato.",
    clickToView: "(Clicca per vedere)",
    statusDist: "Distribuzione Stato",
    registeredEmail: "Email Registrata",
    emailPending: "EMAIL IN ATTESA",
    emailPendingDesc: "Caso in attesa di reclamo.",
    usernameTaken: "Nome preso.",
    usernameShort: "Nome troppo corto.",
    selectCase: "Seleziona caso.",
    googleLoginFailed: "Login Fallito",
    confirmEmail: "Conferma Email",
    confirm: "Conferma",
    edit: "Modifica",
    ensureEmail: "Assicurati che l'email sia corretta.",
    daysAvg: "giorni medi",
    untilToday: "ad oggi",
    glossaryStag: "Legge sulla cittadinanza.",
    glossaryStag5: "Dichiarazione (per discriminazione di genere).",
    glossaryStag15: "Restituzione (Persecuzione nazista).",
    glossaryStag14: "Naturalizzazione discrezionale.",
    glossaryStag10: "Naturalizzazione per residenti.",
    glossaryBva: "Ufficio Federale di Amministrazione.",
    glossaryAkz: "Numero di protocollo.",
    glossaryAkzBreakdown: "Dipartimento, Anno, Data, Numero, Tipo.",
    akzDepartment: "Dipartimento",
    akzYear: "Anno",
    akzDate: "Data",
    akzSequential: "Sequenziale",
    akzType: "Tipo",
    glossaryUrkunde: "Certificato di cittadinanza.",
    glossaryFeststellung: "Determinazione cittadinanza.",
    glossaryArt116: "Articolo 116 (Persecuzione).",
    copyEmail: "Copia Email",
    contactNote: "Nota: Apre client email.",
    lastUpdatedLabel: "Ultimo agg.:",
    privacyTitle: "Privacy Policy",
    acceptPrivacy: "Accetto la policy.",
    privacyLink: "Privacy",
    privacyContent: "Salviamo l'email solo per autenticazione.",
    faqGenDesc: "Genera email per BVA.",
    faqFullName: "Nome Completo",
    faqDob: "Data di Nascita",
    faqSubDate: "Data Invio",
    faqEmbassy: "Consolato",
    faqResidence: "Residenza",
    faqEmailBvaBtn: "Apri Email",
    legalDisclaimer: "Avviso Legale",
    simpleMode: "Modalità Semplice",
    scenicMode: "Modalità Scenica",
    shuffle: "Mescola"
  },
  pt: {
    title: "Rastreador Cidadania Alemã",
    dashboard: "Painel",
    map: "Mapa",
    faq: "FAQ & Glossário",
    aiModel: "Modelo IA",
    myCase: "Meu Caso",
    login: "Entrar",
    logout: "Sair",
    statsTitle: "Estatísticas",
    totalCases: "Total de Casos",
    activeCases: "Casos Ativos",
    pausedCases: "Pausados (>12m)",
    avgProtocol: "Média Envio → AZ",
    avgApproval: "Média AZ → Urkunde",
    avgTotal: "Média Total",
    waitTime: "Tempo de Espera",
    waitingAverage: "Média",
    months: "meses",
    save: "Salvar",
    saving: "Salvando...",
    validationError: "Preencha os campos obrigatórios.",
    country: "País",
    consulate: "Consulado",
    caseType: "Tipo de Caso",
    submissionDate: "Data Envio",
    protocolDate: "Data Protocolo",
    docsDate: "Data Docs",
    approvalDate: "Data Urkunde",
    closedDate: "Data Fechamento",
    status: "Status Atual",
    notifications: "Notificações",
    notifySameDate: "Notificar se mesma data receber AZ",
    notifySameMonth: "Notificar se mesmo mês receber Urkunde",
    notifySubmissionCohort: "Notificar atualizações na minha coorte de envio",
    notifyProtocolCohort: "Notificar atualizações na minha coorte de protocolo",
    notificationTwin: "Um caso de {date} recebeu Protocolo!",
    notificationCohort: "Um caso da sua coorte ({date}) recebeu Urkunde!",
    comments: "Comentários",
    filterCountry: "Filtrar por País",
    filterMonth: "Mês",
    filterYear: "Ano",
    allCountries: "Todos Países",
    allMonths: "Todos Meses",
    allYears: "Todos Anos",
    allTypes: "Todos Tipos",
    disclaimer: "AVISO LEGAL: Projeto privado não oficial.",
    staleWarning: "Caso não atualizado há 12 meses.",
    updateNow: "Atualizar Agora",
    mapInstructions: "Selecione região.",
    admin: "Acesso Criador",
    exportCSV: "Exportar CSV",
    importCSV: "Importar CSV",
    downloadTemplate: "Baixar Modelo",
    adminLogin: "Login Criador",
    enterPin: "Senha",
    accessGranted: "Acesso Permitido",
    successImport: "Sucesso!",
    errorImport: "Erro ao importar.",
    contactOwner: "Contatar Criador",
    contactIntro: "Para erros ou sugestões.",
    contactRedditText: "Contato no Reddit:",
    sendMessage: "Enviar Mensagem",
    yourName: "Seu Nome",
    yourEmail: "Seu Email",
    yourMessage: "Mensagem",
    howToAskAZ: "Como pedir AZ?",
    generateEmail: "Gerar Email",
    docsChecklist: "Lista Documentos",
    progress: "Progresso",
    communityFeed: "Feed Comunidade",
    predictTimeline: "Prever Timeline",
    addToCalendar: "Adicionar Calendário",
    aiPredictionTitle: "Previsão IA",
    aiPredictionDesc: "Estimativa baseada em dados.",
    aiPredictionDescSpecific: "Usando tempos de espera específicos para {type}.",
    estUrkunde: "Data Est. Urkunde",
    stdDev: "Desvio Padrão",
    sampleSize: "Amostra",
    auditLog: "Log Auditoria",
    downloadCard: "Baixar Cartão",
    compareMe: "Comparar vs Média",
    compareMyTime: "Meu Tempo (meses)",
    compareMyWait: "Minha Espera (meses)",
    compareCohortAvg: "Média Coorte (meses)",
    compareDesc: "Comparação com casos aprovados do mesmo período.",
    successTicker: "Aprovados Recentemente",
    shareTitle: "Compartilhe!",
    loginEmailLabel: "Email",
    loginPlaceholder: "email@exemplo.com",
    loginButton: "Continuar com Email",
    loginGoogle: "Entrar com Gmail (Sim)",
    loginOr: "ou",
    loginCheckInbox: "Verifique seu email!",
    loginLinkSent: "Link enviado para",
    loginOpenLink: "Abrir Link",
    loginGoBack: "Voltar",
    loginWait: "Aguardando...",
    cardApplicant: "REQUERENTE",
    cardType: "TIPO",
    cardGenerated: "gerado por tracker-de",
    timelineSubmitted: "Enviado",
    timelineProto: "Protocolo",
    timelineUrkunde: "Urkunde",
    timelineClosed: "Fechado",
    timelineStatus: "Status",
    stepSubmitted: "Enviado",
    stepProtocol: "Protocolo",
    stepDecision: "Decisão",
    maintenance: "Manutenção",
    maintenanceMessage: "Manutenção em andamento.",
    claimPrompt: "Preencheu a planilha? Clique aqui.",
    claimDesc: "Insira seu nome de usuário exato.",
    createPrompt: "Ou crie novo usuário:",
    claimConflictError: "Usuário já existe.",
    welcome: "Bem-vindo!",
    newEmailPrompt: "Email novo. Como prosseguir?",
    createNew: "Criar Novo",
    claimExisting: "Reivindicar Existente",
    createProfileDesc: "Criar perfil para",
    chooseFantasyName: "Escolher Nome",
    searchCase: "Buscar Caso",
    searchPlaceholder: "Buscar...",
    noUnclaimed: "Nenhum caso órfão.",
    cancel: "Cancelar",
    createUser: "Criar Usuário",
    claimCaseBtn: "Reivindicar Caso",
    attention: "Atenção",
    aiAnalysis: "Análise IA",
    filters: "Filtros:",
    showing: "Exibindo:",
    ghostCases: "Casos Fantasma",
    backToActive: "Voltar para Ativos",
    ownerAccess: "Acesso Criador",
    glossary: "Glossário",
    breakdownExample: "Exemplo",
    officialWebsite: "Site Oficial",
    officialDesc: "Acesso a formulários oficiais.",
    visitBva: "Visitar BVA",
    copyText: "Copiar Texto",
    copied: "Copiado!",
    close: "Fechar",
    details: "Detalhes",
    confidence: "Confiança",
    confHigh: "Alta",
    confMedium: "Média",
    confLow: "Baixa",
    avgWait: "Espera Média",
    aiReasoning: "Raciocínio IA",
    runModel: "Rodar Modelo.",
    noCasesFound: "Nenhum caso encontrado.",
    clickToView: "(Clique para ver)",
    statusDist: "Distribuição",
    registeredEmail: "Email Registrado",
    emailPending: "EMAIL PENDENTE",
    emailPendingDesc: "Caso aguardando reivindicação.",
    usernameTaken: "Nome em uso.",
    usernameShort: "Nome muito curto.",
    selectCase: "Selecione um caso.",
    googleLoginFailed: "Falha no Login",
    confirmEmail: "Confirmar Email",
    confirm: "Confirmar",
    edit: "Editar",
    ensureEmail: "Verifique se o email está correto.",
    daysAvg: "dias média",
    untilToday: "até hoje",
    glossaryStag: "Lei de Cidadania.",
    glossaryStag5: "Declaração (gênero).",
    glossaryStag15: "Restituição (Nazismo).",
    glossaryStag14: "Naturalização discricionária.",
    glossaryStag10: "Naturalização por residência.",
    glossaryBva: "Escritório Federal de Administração.",
    glossaryAkz: "Número de protocolo.",
    glossaryAkzBreakdown: "Dep, Ano, Data, Num, Tipo.",
    akzDepartment: "Departamento",
    akzYear: "Ano",
    akzDate: "Data",
    akzSequential: "Sequencial",
    akzType: "Tipo",
    glossaryUrkunde: "Certificado de Cidadania.",
    glossaryFeststellung: "Determinação.",
    glossaryArt116: "Artigo 116.",
    copyEmail: "Copiar Email",
    contactNote: "Nota: Abre cliente de email.",
    lastUpdatedLabel: "Atualizado:",
    privacyTitle: "Política de Privacidade",
    acceptPrivacy: "Aceito a política.",
    privacyLink: "Privacidade",
    privacyContent: "Armazenamos email apenas para login.",
    faqGenDesc: "Gera email para o BVA.",
    faqFullName: "Nome Completo",
    faqDob: "Data Nasc.",
    faqSubDate: "Data Envio",
    faqEmbassy: "Consulado",
    faqResidence: "Residência",
    faqEmailBvaBtn: "Abrir Email",
    legalDisclaimer: "Aviso Legal",
    simpleMode: "Modo Simples",
    scenicMode: "Modo Cênico",
    shuffle: "Aleatório"
  }
};
